services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: test_password
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./backend/authentification_service
    environment:
      DATABASE_URL: postgresql://test_user:test_password@db:5432/test_db
      JWT_SECRET: test_jwt_secret
      JWT_EXPIRES_IN: 3600
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  data-service:
    build: ./backend/data_service
    environment:
      DATABASE_URL: postgresql://test_user:test_password@db:5432/test_db
      STORAGE_DIR: /app/storage
    ports:
      - "8002:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./test_storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  processing-service:
    build: ./backend/processing_service
    environment:
      STORAGE_DIR: /app/storage
    ports:
      - "8003:8000"
    volumes:
      - ./test_storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - data-service
      - processing-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - data-service
      - processing-service
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3