apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: project-sw
data:
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/scidata"
  POSTGRES_DB: "scidata"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  DATA_SERVICE_URL: "http://data-service:8001"
  PROCESSING_SERVICE_URL: "http://processing-service:8002"
